Vite
ome/omero-figure pull request #477
Opened 2022-08-12 10:04 UTC by will-moore

Work in progress... This is going to take a while....!

This is a re-build of omero-figure to update all dependencies to their latest versions, including:
 - jQuery
 - Bootstrap UI framework - including all new bootstrap-icons
 - Underscore
 - Raphael

I'm also taking the opportunity to upgrade the build system to use https://vitejs.dev/ instead of `grunt`, and all JavaScript will be imported ES modules now (no global variables etc).

This will give us a JS-based dev server during development (similar to iviewer), and allow development without needing to install `omero-web`.

I couldn't work out how to include jquery-UI in the build (needed for sliders and 'draggable' behaviour). I'd like to remove the use of jquery-UI and use native range input for sliders, as I did on https://github.com/will-moore/omero-player
Also, https://github.com/itsjavi/bootstrap-colorpicker is EOL (won't run on latest Bootstrap) so will need an alternative.

Most other technical questions seem to be resolved now, but still a lot of code to convert.

Dev workflow:

```
$ npm install

# to server at localhost:8080
$ npm run start

# to build and put everything in place for omero-web to serve
$ npm run build
```

2023-01-12 15:43 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-plugins-push#1393](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1393/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1393/consoleText) for more details.
Possible conflicts:
  - PR #471 will-moore 'Use thumbnail if scaled region too large'
    - omero_figure/views.py

--conflicts

2024-02-19 15:28 UTC, will-moore commented
@Rdornier @Tom-TBT - This big rewrite PR is getting close to being ready so this is a heads-up...

 - See description above for a summary, and see the README for updated dev workflow.
 - I have rebased all PRs from the last release and earlier. In some cases this was quite manual, so that functionality will need retesting (along with ALL the other functionality of OMERO.figure)!
 - I'll do the same with PRs that have already been opened and merged for 6.2.0 release (https://github.com/ome/omero-figure/milestone/17)
 - Since Shape-Editor is now included in this repo, I've also copied over the 2 PRs from Remy there. I need to discus with @jburel whether we will release shape-editor on npm and include those PRs in a figure release before this PR, or simply wait until this PR is released.
 - I'm hoping that we can get this PR tested, merged and released as e.g. `6.3.0` reasonably soon - Therefore I'd like you to open any new PRs on top of this branch, so as to avoid future rebasing/merging etc.
 - If you are able to spare any time to help with testing, that would be great?

2024-02-26 10:29 UTC, Tom-TBT commented
Hi Will, here are a few issues I spotted:

- Max intensity projection sliders are broken. I always end up with one slider not wanting to move anymore (it jumps back to where I grabbed it from)
- ROIs are filled with white at the export.
- When there are inherited tags, nothing appears. In that case I found the culprit:
https://github.com/will-moore/figure/blob/4487c2479670cbe13180af83f0652bb046f71baa/src/js/models/panel_model.js#L1045

`for(j = 0; j < lineage.length; j++){` should change to `for(let j = 0; j < lineage.length; j++){`
I don't know why this PR broke it, but that was an error from me, my apologies.

2024-02-26 11:54 UTC, will-moore commented
@Tom-TBT Thanks for the feedback, I'll look at fixing those.
The PR "broke" your code because it's now "strict" mode and it no-longer allows global variables to be declared (without the `let` to restrict it's scope). This prevents accidentally getting global variables overwriting each other etc.

2024-02-27 08:46 UTC, Rdornier commented
Hello Will,

I'm not able to test it with the new development environnement. How do you configure the CORS ? My localhost:4080 is running but there is no communication with localhost:8080.

Thanks,
Rémy.

2024-02-29 17:25 UTC, will-moore commented
@Rdornier The various web install pages have info on enabling CORS e.g. https://omero.readthedocs.io/en/stable/sysadmins/unix/install-web/walkthrough/omeroweb-install-centos7-ice3.6.html#setting-up-cors 
The https://github.com/adamchainz/django-cors-headers should already be installed as a dependency of omero-web.

When you `npm run start` you should get the usual OMERO.figure entry dialog at localhost:8080 and if you choose "Open Figure" then it'll try to load from http://localhost:4080/figure/list_web_figures/.
You should already be logged-in to the webclient so that if you were to open that URL in a new browser it works (returns JSON).
You should see that the figure app tries to load it, and if you've got CORs setup right, it'll be able to read the response (which have correct headers):

![Screenshot 2024-02-29 at 17 17 04](https://github.com/ome/omero-figure/assets/900055/a4f54500-de49-4703-a228-907119b2dbf8)

If not, then you'll get some CORs error.
You can ignore the other failed requests before that (for openwith...).

2024-03-18 10:00 UTC, Tom-TBT commented on src/.env
I saw in `Help -> About OMERO.figure` that the version shown is 4.4.4.dev0. It matches the VITE_VERSION here

2024-03-18 10:05 UTC, Tom-TBT commented
Hello Will,
I tested the PR again today. The previous bug with the Z projection sliders is fixed, but I saw today that I can pass the "top slider" under the "bottom slider" (this is not the case for the previous OMERO-figure version).

2024-03-19 13:13 UTC, will-moore commented
@Tom-TBT - should be fixed now.
The `<input type='range'/>` sliders that we're using now don't have quite the same behaviour as jQuery-UI sliders. I have fixed the sliding handles past each other, but we're still missing the click-handling on the slider (to slide a handle to where you clicked). Hopefully that's not an essential feature, although it probably could be done...

2024-03-20 16:20 UTC, will-moore commented
@Tom-TBT - I have added click-handling so the range sliders (channels and z-projection) should behave the same as the did before with jQuery sliders - The handle nearest to the point you clicked is moved to where you clicked.

2024-04-05 12:55 UTC, pwalczysko commented
Bug: Copying of ROIs is reported to be outside of viewport, although it is not.

1. Open a large svs image in figure. For example, the saved figure is https://merge-ci.openmicroscopy.org/web/figure/file/2525 (user-3). Add some ROIs from OMERO, concentrated on one spot (some five ROIs added within a very small area). 
2. Go back to webclient, get link to the same image and add this image into the same figure.
3. Select the panel where you added ROIs to, go to Labels tab, click Copy on the ROIs section.
4. Select the panel with the newly added image. Go to Labels tab, click Paste in the ROIs section.
5. Observe dialog saying ``Some shapes may be outside the visible 'viewport' of panel. Target image may be too small or zoomed in too much. Try zooming out before pasting again, or paste to a bigger image.`` -> not expected, the zooming of the second panel is not too large, the ROIs could have been copied, they are not near the edge, see figure is https://merge-ci.openmicroscopy.org/web/figure/file/2525 (user-3)

2024-04-05 12:59 UTC, pwalczysko commented
Sorry, deleted the comment which was reporting a bug of copy and paste of ROIs. This was caused by me using a smaller screenshot of the same image - the behaviour is as expected.

2024-04-12 13:32 UTC, pwalczysko commented
![Screenshot 2024-04-12 at 14 24 57](https://github.com/ome/omero-figure/assets/2478303/e88e26eb-973d-46df-95c0-9f910c69001e)

Firefox, Mac M1 - ^^^ these sliders look strange, the left-hand side min slider

2024-04-12 13:32 UTC, pwalczysko requested changes
Please address the sliders issue in Preview panel. https://github.com/ome/omero-figure/pull/477#issuecomment-2051771296 and the spacing as per https://github.com/ome/omero-figure/pull/477#issuecomment-2051784935

2024-04-12 13:40 UTC, pwalczysko commented
![Screenshot 2024-04-12 at 14 38 05](https://github.com/ome/omero-figure/assets/2478303/53ec0e6b-95dd-4465-92d6-7f512ed078c5)

Firefox, Mac, any image ^^^ ``Edit labels`` header is a bit squished into the box above it - this is different than without this PR, which is 
![Screenshot 2024-04-12 at 14 39 47](https://github.com/ome/omero-figure/assets/2478303/48e589a3-501a-4d01-96ab-eaf2006dec04)

Could a proper spacing be added ?

2024-04-12 14:57 UTC, will-moore commented
@pwalczysko - thanks for the testing.

Slider handle positions (https://github.com/ome/omero-figure/pull/477#issuecomment-2051771296) was actually caused by a different PR giving wrong values for `min` (-2147483648), so the slider minimum value was very low, causing the handles to overlap at the top. See https://github.com/ome/omero-web/pull/536#issuecomment-2051902359 (fixed now, but will need image panels to be removed or updated since they will still contain the wrong values).

The thick sliders in Firefox is fixed by b7cfdfa above and the `Edit Labels` spacing is also fixed now.

2024-04-17 17:53 UTC, pwalczysko commented
> fixed now, but will need image panels to be removed or updated since they will still contain the wrong values).

You mean panels in pre-existing figures ? i.e. when a figure was created on merge-ci after the https://github.com/ome/omero-web/pull/536 was open, but before your fix https://github.com/ome/omero-web/pull/536#issuecomment-2051902359, then the panels contain wrong values, do i get it right ? Panels updated or created before or after this period should contain correct values ?

2024-04-17 18:04 UTC, pwalczysko commented
> The thick sliders in Firefox is fixed by [b7cfdfa](https://github.com/ome/omero-figure/commit/b7cfdfad81c856135bb437886f1cc27c83987469) above and the `Edit Labels` spacing is also fixed now.

Confirming this fix.



> Slider handle positions

Yes, these are fixed. Really not sure about the value remark https://github.com/ome/omero-figure/pull/477#issuecomment-2061886758

2024-04-17 18:05 UTC, pwalczysko requested changes
Please explain about https://github.com/ome/omero-figure/pull/477#issuecomment-2061886758. Thanks

2024-04-17 18:10 UTC, pwalczysko commented
Really cannot say that this is caused by this PR, but on merge-ci (ie. not for example on outreach), when I open a Figure it opens in a new tab (expected). But, only on merge-ci, this new tab is not marked with the OMERO logo.

merge-ci (webclient tab leftmost, OMERO.figure tabs to the right of it)
![Screenshot 2024-04-17 at 19 01 04](https://github.com/ome/omero-figure/assets/2478303/0d8a6644-63e3-4b20-abdf-a4e1c854e5a8)

outreach server (both webclient tab and figure tab to its right have OMERO logo):

![Screenshot 2024-04-17 at 19 09 50](https://github.com/ome/omero-figure/assets/2478303/51bc1282-af8b-4e84-9ede-d4387518e0e2)

2024-04-19 13:00 UTC, will-moore commented
The `favicon.ico` is configured by the omero-web framework itself and not by the apps (iviewer/figure) at https://github.com/ome/omero-web/blob/02bd670ca7628ecb293108f394ef062a66a7beb4/omeroweb/settings.py#L867.
I'm not sure why it's not working on merge-ci but it's not related to this PR.

2024-04-19 13:02 UTC, will-moore commented
Re: https://github.com/ome/omero-figure/pull/477#issuecomment-2061886758 - as discussed, you are correct that this was a temporary bug caused by https://github.com/ome/omero-web/pull/536 and won't affect any users.

2024-04-19 13:10 UTC, pwalczysko commented
> Re: [#477 (comment)](https://github.com/ome/omero-figure/pull/477#issuecomment-2061886758) - as discussed, you are correct that this was a temporary bug caused by [ome/omero-web#536](https://github.com/ome/omero-web/pull/536) and won't affect any users.

Understood, thank you.

2024-04-29 12:21 UTC, jburel commented
Merging so we can move forward

2024-04-29 12:21 UTC, merged